server:
  port: 8992

spring:
  application:
    name: CustomerCenter  #项目名称(Redis缓存Key等将以此为前缀以避免冲突)
    version: 1.0
  #进行全局配置，将日期格式为:yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  profiles:
  #    active: #help.profile#      #运行环境占位符,打包时被替代
  main:
    show-banner: true # 是否显示banner，可选值[true|false]
  cloud:
    nacos:
      config:
        server-addr: ${nacos.server-addr}:${nacos.port}
      discovery:
        enabled: true
        register-enabled: true
        server-addr: ${nacos.server-addr}:${nacos.port}
    sentinel:
      transport:
        dashboard: 192.168.8.129:8080 #sentinel dashboard的访问地址
      eager: true #取消Sentinel控制台懒加载
      datasource:
        ds:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr} #nacos的访问地址
            dataId: ${spring.application.name}-sentinel #nacos中存储规则的dataId
            groupId: DEFAULT_GROUP #nacos中存储规则的groupId
            rule-type: FLOW #该参数是spring cloud alibaba升级到0.2.2之后增加的配置，用来定义存储的规则类型

#==================== 日志配合·标准  ============================
logging:
  config: classpath:log4j2-spring.xml
  level:
    root: debug

####################################### Nacos 配置 #######################################
nacos:
  server-addr: 192.168.8.129
  port: 8848